steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/coil-sa/rafiki-money-frontend:$SHORT_SHA", "./packages/frontend/"]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/coil-sa/rafiki-money-frontend:$SHORT_SHA"]
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - set
      - image
      - deployment
      - frontend
      - 'rafiki-money-frontend-sha256-1=gcr.io/coil-sa/rafiki-money-frontend:$SHORT_SHA'
      - --namespace=rafiki-money
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=rafiki-cluster'
