steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/coil-sa/rafiki-money-backend:$SHORT_SHA", "./packages/backend/"]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/coil-sa/rafiki-money-backend:$SHORT_SHA"]
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - set
      - image
      - deployment
      - backend
      - 'rafiki-money-backend-sha256-1=gcr.io/coil-sa/rafiki-money-backend:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=rafiki-cluster'
