import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home () {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            We&apos;re working hard on building a new testing and development
            environemt based on{' '}
            <a className={styles.code} href="https://github.com/interledger/rafiki">Rafiki</a> and the{' '}
            <a className={styles.code} href="https://docs.openpayments.guide/">Open Payments APIs</a>.
          </p>
          <div>
            <a
              href="https://interledger.org"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/interledger.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/favicon.svg"
            alt="rafiki.money Logo"
            width={500}
            height={400}
            priority
          />
        </div>

        <div className={styles.grid}>
          <h2 className={inter.className}>
            rafiki.money <span>-&gt;</span>
          </h2>
          <p className={inter.className}>
            We&apos;ve deprecated this service, and are working on building a
            new version of an Interledger testnet. Please check back later in
            2023 for a preview.
          </p>
        </div>
      </main>
    </>
  )
}
