
hydra:
  # Number of ORY Hydra members
  replicaCount: 1

  image:
    # ORY Hydra image
    repository: oryd/hydra
    # ORY Hydra version
    tag: v1.3.2
    # Image pull policy
    pullPolicy: IfNotPresent

  # Image pull secrets
  imagePullSecrets: []
  # Chart name override
  nameOverride: ""
  # Full chart name override
  fullnameOverride: ""

  # Configures the Kubernetes service
  service:
    # Configures the Kubernetes service for the proxy port.
    public:
      # En-/disable the service
      enabled: true
      # The service type
      type: ClusterIP
      # The service port
      port: 4444
      # If you do want to specify annotations, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'annotations:'.
      annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    # Configures the Kubernetes service for the api port.
    admin:
      # En-/disable the service
      enabled: true
      # The service type
      type: ClusterIP
      # The service port
      port: 4445
      # If you do want to specify annotations, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'annotations:'.
      annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"

  # Configure ingress
  ingress:
    # Configure ingress for the proxy port.
    public:
      # En-/Disable the proxy ingress.
      enabled: enable
      annotations:
         kubernetes.io/ingress.class: nginx
      #     kubernetes.io/tls-acme: "true"
      hosts:
        - host: auth.rafiki.money
          paths: ["/"]
    #    tls: []
    #        hosts:
    #          - proxy.hydra.local
    #      - secretName: hydra-proxy-example-tls

    admin:
      # En-/Disable the api ingress.
      enabled: false

      annotations:
            kubernetes.io/ingress.class: nginx
      hosts:
        - host: auth.rafiki.money
          paths: ["/admin"]
  #    tls: []
  #      hosts:
  #        - api.hydra.local
  #      - secretName: hydra-api-example-tls


  # Configure ORY Hydra itself
  hydra:
    # The ORY Hydra configuration. For a full list of available settings, check:
    #   https://github.com/ory/hydra/blob/master/docs/config.yaml
    config:
      dsn: memory
      serve:
        public:
          port: 4444
        admin:
          port: 4445
        tls:
          allow_termination_from:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
      secrets: {}
      urls:
        login: https://rafiki.money/login
        consent: https://rafiki.money/consent
        logout: https://rafiki.money/logout
        self:
          issuer: http://auth.rafiki.money

    autoMigrate: true
    dangerousForceHttp: true
    dangerousAllowInsecureRedirectUrls: false

  # Configures controller setup
  maester:
    enabled: false
