module.exports = {
  prefix: '',
  important: false,
  separator: ':',
  theme: {
    fontFamily: {
      display: 'Rubik, sans-serif',
      body: 'Rubik, sans-serif'
    },
    minWidth: {
      '64': '64px'
    },
    colors: {
      transparent: 'transparent',
      black: '#000',
      white: '#fff'
    },
    extend: {
      fontSize: {
        'overline': '0.625rem',
        'caption': '.75rem',
        'button': '0.875rem',
        'body-2': '0.875rem',
        'body-1': '1rem',
        'subtitle-2': '0.875rem',
        'subtitle-1': '1rem',
        'headline-6': '1.25rem',
        'headline-5': '1.5rem',
        'headline-4': '2.125rem',
        'headline-3': '3rem',
        'headline-2': '3.75rem',
        'headline-1': '6rem',
      },
      screens: {
        'dark-mode': {'raw': '(prefers-color-scheme: dark)'},
      },
      opacity: {
        '12': '.12',
        '38': '.38'
      },
      colors: {
        primary: {
          '100': '#FFCCBC',
          '200': '#FFAA91',
          default: '#FF8A65',
          '400': '#F6744C',
          '500': '#E96139',
        },
        secondary: {
          '100': '#B0EBE4',
          '200': '#77E0D3',
          default: '#21D2BF',
          '400': '#00C6b0',
          '500': '#00B9A0',
        },
        error: '#B00020',
        red: '#EB5757',
        orange: '#F2994A',
        yellow: '#F2C94C',
        green: '#2FAE60',
        blue: '#2F80ED',
        purple: '#9B51E0',
        dark: {
          primary: {
            '100': '#FAEDEB',
            '200': '#FDD4C7',
            default: '#FEB9A3',
            '400': '#FF9E7C',
            '500': '#FF885B',
          },
          secondary: {
            '100': '#E0F8F7',
            '200': '#B2EEE8',
            default: '#7AE4D9',
            '400': '#3AD7C8',
            '500': '#00CBB9',
          },
          error: '#CF6679',
          red: '#F39B9B',
          orange: '#F7C192',
          yellow: '#F7DE92',
          green: '#8AE5B1',
          blue: '#77ACF3',
          purple: '#C193EC',
        },
      },
    },
  },
  variants: {
    accessibility: ['responsive', 'focus'],
    alignContent: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: ['responsive'],
    appearance: ['responsive'],
    backgroundAttachment: ['responsive'],
    backgroundColor: ['responsive', 'hover', 'focus', 'active'],
    backgroundPosition: ['responsive'],
    backgroundRepeat: ['responsive'],
    backgroundSize: ['responsive'],
    borderCollapse: ['responsive'],
    borderColor: ['responsive', 'hover', 'focus'],
    borderRadius: ['responsive'],
    borderStyle: ['responsive'],
    borderWidth: ['responsive'],
    boxShadow: ['responsive', 'hover', 'focus'],
    boxSizing: ['responsive'],
    cursor: ['responsive'],
    display: ['responsive'],
    fill: ['responsive'],
    flex: ['responsive'],
    flexDirection: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    flexWrap: ['responsive'],
    float: ['responsive'],
    clear: ['responsive'],
    fontFamily: ['responsive'],
    fontSize: ['responsive'],
    fontSmoothing: ['responsive'],
    fontStyle: ['responsive'],
    fontWeight: ['responsive', 'hover', 'focus'],
    height: ['responsive'],
    inset: ['responsive'],
    justifyContent: ['responsive'],
    letterSpacing: ['responsive'],
    lineHeight: ['responsive'],
    listStylePosition: ['responsive'],
    listStyleType: ['responsive'],
    margin: ['responsive'],
    maxHeight: ['responsive'],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: ['responsive'],
    objectFit: ['responsive'],
    objectPosition: ['responsive'],
    opacity: ['responsive', 'hover', 'focus'],
    order: ['responsive'],
    outline: ['responsive', 'focus'],
    overflow: ['responsive'],
    padding: ['responsive'],
    placeholderColor: ['responsive', 'focus'],
    pointerEvents: ['responsive'],
    position: ['responsive'],
    resize: ['responsive'],
    stroke: ['responsive'],
    strokeWidth: ['responsive'],
    tableLayout: ['responsive'],
    textAlign: ['responsive'],
    textColor: ['responsive', 'hover', 'focus'],
    textDecoration: ['responsive', 'hover', 'focus'],
    textTransform: ['responsive'],
    userSelect: ['responsive'],
    verticalAlign: ['responsive'],
    visibility: ['responsive'],
    whitespace: ['responsive'],
    width: ['responsive'],
    wordBreak: ['responsive'],
    zIndex: ['responsive'],
    gap: ['responsive'],
    columnGap: ['responsive'],
    rowGap: ['responsive'],
    gridAutoFlow: ['responsive'],
    gridTemplateColumns: ['responsive'],
    gridColumn: ['responsive'],
    gridColumnStart: ['responsive'],
    gridColumnEnd: ['responsive'],
    gridTemplateRows: ['responsive'],
    gridRow: ['responsive'],
    gridRowStart: ['responsive'],
    gridRowEnd: ['responsive'],
    transform: ['responsive'],
    transformOrigin: ['responsive'],
    scale: ['responsive', 'hover', 'focus'],
    rotate: ['responsive', 'hover', 'focus'],
    translate: ['responsive', 'hover', 'focus'],
    skew: ['responsive', 'hover', 'focus'],
    transitionProperty: ['responsive'],
    transitionTimingFunction: ['responsive'],
    transitionDuration: ['responsive'],
  },
  corePlugins: {},
  plugins: [
    require('tailwindcss-elevation')(['responsive', 'hover', 'focus', 'active']),
    require('tailwindcss-dark-mode')(),
  ],
}